import type { BuilderServerApiEndpoint } from "@shared/api";

function param(
  name: string,
  label: string,
  location: BuilderServerApiEndpoint["params"][number]["location"],
  required: boolean,
  valueType: BuilderServerApiEndpoint["params"][number]["valueType"],
  description: string,
) {
  return {
    name,
    label,
    location,
    required,
    valueType,
    description,
  } satisfies BuilderServerApiEndpoint["params"][number];
}

function endpoint(
  definition: BuilderServerApiEndpoint,
): BuilderServerApiEndpoint {
  return definition;
}

export const BUILDER_API_CATALOG: BuilderServerApiEndpoint[] = [
  endpoint({
    id: "auth-login",
    category: "Auth",
    name: "Sign in",
    description: "Create a server session and issue the auth cookie for the current user.",
    method: "POST",
    path: "/api/auth/login",
    requiresAuth: false,
    allowedRoles: [],
    params: [
      param("username", "Username", "body", true, "string", "Workspace username."),
      param("password", "Password", "body", true, "string", "Workspace password."),
    ],
    successMessage: "Signed in successfully",
  }),
  endpoint({
    id: "auth-me",
    category: "Auth",
    name: "Current session",
    description: "Return the currently authenticated workspace user if a session exists.",
    method: "GET",
    path: "/api/auth/me",
    requiresAuth: false,
    allowedRoles: [],
    params: [],
    successMessage: "Loaded current session",
  }),
  endpoint({
    id: "auth-logout",
    category: "Auth",
    name: "Sign out",
    description: "Clear the active auth cookie and remove the persisted server session.",
    method: "POST",
    path: "/api/auth/logout",
    requiresAuth: false,
    allowedRoles: [],
    params: [],
    successMessage: "Signed out successfully",
  }),
  endpoint({
    id: "ping",
    category: "Utility",
    name: "Ping",
    description: "Basic health check endpoint.",
    method: "GET",
    path: "/api/ping",
    requiresAuth: false,
    allowedRoles: [],
    params: [],
    successMessage: "Ping completed",
  }),
  endpoint({
    id: "demo",
    category: "Utility",
    name: "Demo response",
    description: "Simple demo endpoint used for basic client/server tests.",
    method: "GET",
    path: "/api/demo",
    requiresAuth: false,
    allowedRoles: [],
    params: [],
    successMessage: "Demo response loaded",
  }),
  endpoint({
    id: "menus-list",
    category: "Menus",
    name: "List menus",
    description: "Return all menus available to the current operator or admin.",
    method: "GET",
    path: "/api/menus",
    requiresAuth: true,
    allowedRoles: ["admin", "operator"],
    params: [],
    successMessage: "Menus loaded",
  }),
  endpoint({
    id: "menus-get",
    category: "Menus",
    name: "Get menu by id",
    description: "Return a single menu by id.",
    method: "GET",
    path: "/api/menus/:id",
    requiresAuth: true,
    allowedRoles: ["admin", "operator"],
    params: [
      param("id", "Menu ID", "path", true, "string", "Menu identifier."),
    ],
    successMessage: "Menu loaded",
  }),
  endpoint({
    id: "menus-create",
    category: "Menus",
    name: "Create menu",
    description: "Create a new menu record.",
    method: "POST",
    path: "/api/menus",
    requiresAuth: true,
    allowedRoles: ["admin", "operator"],
    params: [
      param("name", "Name", "body", true, "string", "Menu name."),
      param("location", "Location", "body", true, "string", "Store or venue location."),
      param("items", "Items", "body", false, "array", "Array of menu items."),
    ],
    successMessage: "Menu created",
  }),
  endpoint({
    id: "menus-update",
    category: "Menus",
    name: "Update menu",
    description: "Update an existing menu record.",
    method: "PUT",
    path: "/api/menus/:id",
    requiresAuth: true,
    allowedRoles: ["admin", "operator"],
    params: [
      param("id", "Menu ID", "path", true, "string", "Menu identifier."),
      param("name", "Name", "body", false, "string", "Updated menu name."),
      param("location", "Location", "body", false, "string", "Updated menu location."),
      param("items", "Items", "body", false, "array", "Updated item array."),
    ],
    successMessage: "Menu updated",
  }),
  endpoint({
    id: "menus-delete",
    category: "Menus",
    name: "Delete menu",
    description: "Delete an existing menu record.",
    method: "DELETE",
    path: "/api/menus/:id",
    requiresAuth: true,
    allowedRoles: ["admin"],
    params: [
      param("id", "Menu ID", "path", true, "string", "Menu identifier."),
    ],
    successMessage: "Menu deleted",
  }),
  endpoint({
    id: "rewards-list",
    category: "Rewards",
    name: "List rewards",
    description: "Return all reward programs.",
    method: "GET",
    path: "/api/rewards",
    requiresAuth: true,
    allowedRoles: ["admin", "operator"],
    params: [],
    successMessage: "Reward programs loaded",
  }),
  endpoint({
    id: "rewards-get",
    category: "Rewards",
    name: "Get reward program",
    description: "Return a single reward program by id.",
    method: "GET",
    path: "/api/rewards/:id",
    requiresAuth: true,
    allowedRoles: ["admin", "operator"],
    params: [
      param("id", "Program ID", "path", true, "string", "Reward program identifier."),
    ],
    successMessage: "Reward program loaded",
  }),
  endpoint({
    id: "rewards-create",
    category: "Rewards",
    name: "Create reward program",
    description: "Create a new loyalty reward program.",
    method: "POST",
    path: "/api/rewards",
    requiresAuth: true,
    allowedRoles: ["admin", "operator"],
    params: [
      param("name", "Name", "body", true, "string", "Reward program name."),
      param("pointsPerDollar", "Points per dollar", "body", true, "number", "Earn rate."),
      param("tiers", "Tiers", "body", false, "array", "Tier definitions."),
      param("redemptions", "Redemptions", "body", false, "array", "Redemption options."),
    ],
    successMessage: "Reward program created",
  }),
  endpoint({
    id: "rewards-update",
    category: "Rewards",
    name: "Update reward program",
    description: "Update an existing loyalty reward program.",
    method: "PUT",
    path: "/api/rewards/:id",
    requiresAuth: true,
    allowedRoles: ["admin", "operator"],
    params: [
      param("id", "Program ID", "path", true, "string", "Reward program identifier."),
      param("name", "Name", "body", false, "string", "Reward program name."),
      param("pointsPerDollar", "Points per dollar", "body", false, "number", "Updated earn rate."),
      param("tiers", "Tiers", "body", false, "array", "Updated tiers."),
      param("redemptions", "Redemptions", "body", false, "array", "Updated redemption options."),
    ],
    successMessage: "Reward program updated",
  }),
  endpoint({
    id: "rewards-delete",
    category: "Rewards",
    name: "Delete reward program",
    description: "Delete a reward program by id.",
    method: "DELETE",
    path: "/api/rewards/:id",
    requiresAuth: true,
    allowedRoles: ["admin", "operator"],
    params: [
      param("id", "Program ID", "path", true, "string", "Reward program identifier."),
    ],
    successMessage: "Reward program deleted",
  }),
  endpoint({
    id: "members-list",
    category: "Members",
    name: "List members",
    description: "Return a paginated list of members.",
    method: "GET",
    path: "/api/members",
    requiresAuth: true,
    allowedRoles: ["admin", "operator"],
    params: [
      param("page", "Page", "query", false, "number", "Page number."),
      param("limit", "Limit", "query", false, "number", "Items per page."),
    ],
    successMessage: "Members loaded",
  }),
  endpoint({
    id: "members-get",
    category: "Members",
    name: "Get member",
    description: "Return a single member by id.",
    method: "GET",
    path: "/api/members/:id",
    requiresAuth: true,
    allowedRoles: ["admin", "operator"],
    params: [
      param("id", "Member ID", "path", true, "string", "Member identifier."),
    ],
    successMessage: "Member loaded",
  }),
  endpoint({
    id: "members-create",
    category: "Members",
    name: "Create member",
    description: "Create a new loyalty member record.",
    method: "POST",
    path: "/api/members",
    requiresAuth: true,
    allowedRoles: ["admin", "operator"],
    params: [
      param("email", "Email", "body", true, "string", "Member email address."),
      param("name", "Name", "body", true, "string", "Member full name."),
      param("phone", "Phone", "body", false, "string", "Member phone number."),
    ],
    successMessage: "Member created",
  }),
  endpoint({
    id: "members-update",
    category: "Members",
    name: "Update member",
    description: "Update a member record by id.",
    method: "PUT",
    path: "/api/members/:id",
    requiresAuth: true,
    allowedRoles: ["admin", "operator"],
    params: [
      param("id", "Member ID", "path", true, "string", "Member identifier."),
      param("email", "Email", "body", false, "string", "Updated email."),
      param("name", "Name", "body", false, "string", "Updated name."),
      param("phone", "Phone", "body", false, "string", "Updated phone."),
      param("loyaltyPoints", "Loyalty points", "body", false, "number", "Updated points balance."),
      param("tier", "Tier", "body", false, "string", "Updated tier label."),
    ],
    successMessage: "Member updated",
  }),
  endpoint({
    id: "members-delete",
    category: "Members",
    name: "Delete member",
    description: "Delete a member by id.",
    method: "DELETE",
    path: "/api/members/:id",
    requiresAuth: true,
    allowedRoles: ["admin"],
    params: [
      param("id", "Member ID", "path", true, "string", "Member identifier."),
    ],
    successMessage: "Member deleted",
  }),
  endpoint({
    id: "members-add-points",
    category: "Members",
    name: "Add member points",
    description: "Increment a member points balance.",
    method: "POST",
    path: "/api/members/:id/points",
    requiresAuth: true,
    allowedRoles: ["admin", "operator"],
    params: [
      param("id", "Member ID", "path", true, "string", "Member identifier."),
      param("points", "Points", "body", true, "number", "Points to add."),
    ],
    successMessage: "Member points updated",
  }),
  endpoint({
    id: "branding-list",
    category: "Branding",
    name: "List branding configs",
    description: "Return all saved white-label branding configurations.",
    method: "GET",
    path: "/api/branding",
    requiresAuth: true,
    allowedRoles: ["admin", "designer"],
    params: [],
    successMessage: "Branding configs loaded",
  }),
  endpoint({
    id: "branding-get",
    category: "Branding",
    name: "Get branding config",
    description: "Return a branding configuration by id.",
    method: "GET",
    path: "/api/branding/:id",
    requiresAuth: true,
    allowedRoles: ["admin", "designer"],
    params: [
      param("id", "Brand ID", "path", true, "string", "Brand configuration identifier."),
    ],
    successMessage: "Branding config loaded",
  }),
  endpoint({
    id: "branding-create",
    category: "Branding",
    name: "Create branding config",
    description: "Create a new white-label branding configuration.",
    method: "POST",
    path: "/api/branding",
    requiresAuth: true,
    allowedRoles: ["admin", "designer"],
    params: [
      param("brandName", "Brand name", "body", true, "string", "Display brand name."),
      param("primaryColor", "Primary color", "body", true, "string", "Primary hex color."),
      param("secondaryColor", "Secondary color", "body", true, "string", "Secondary hex color."),
      param("accentColor", "Accent color", "body", true, "string", "Accent hex color."),
      param("logo", "Logo", "body", false, "string", "Brand logo or base64 asset."),
      param("favicon", "Favicon", "body", false, "string", "Favicon asset."),
      param("customDomain", "Custom domain", "body", false, "string", "Brand domain."),
      param("fontFamily", "Font family", "body", false, "string", "Font preset."),
    ],
    successMessage: "Branding config created",
  }),
  endpoint({
    id: "branding-update",
    category: "Branding",
    name: "Update branding config",
    description: "Update an existing branding configuration.",
    method: "PUT",
    path: "/api/branding/:id",
    requiresAuth: true,
    allowedRoles: ["admin", "designer"],
    params: [
      param("id", "Brand ID", "path", true, "string", "Brand configuration identifier."),
      param("brandName", "Brand name", "body", false, "string", "Display brand name."),
      param("primaryColor", "Primary color", "body", false, "string", "Primary hex color."),
      param("secondaryColor", "Secondary color", "body", false, "string", "Secondary hex color."),
      param("accentColor", "Accent color", "body", false, "string", "Accent hex color."),
      param("logo", "Logo", "body", false, "string", "Brand logo or base64 asset."),
      param("favicon", "Favicon", "body", false, "string", "Favicon asset."),
      param("customDomain", "Custom domain", "body", false, "string", "Brand domain."),
      param("fontFamily", "Font family", "body", false, "string", "Font preset."),
    ],
    successMessage: "Branding config updated",
  }),
  endpoint({
    id: "branding-delete",
    category: "Branding",
    name: "Delete branding config",
    description: "Delete a branding configuration by id.",
    method: "DELETE",
    path: "/api/branding/:id",
    requiresAuth: true,
    allowedRoles: ["admin", "designer"],
    params: [
      param("id", "Brand ID", "path", true, "string", "Brand configuration identifier."),
    ],
    successMessage: "Branding config deleted",
  }),
  endpoint({
    id: "users-list",
    category: "Users",
    name: "List users",
    description: "Return all internal workspace users.",
    method: "GET",
    path: "/api/users",
    requiresAuth: true,
    allowedRoles: ["admin"],
    params: [],
    successMessage: "Users loaded",
  }),
  endpoint({
    id: "site-brand-get",
    category: "Site Config",
    name: "Get site brand",
    description: "Return the current site-wide brand settings.",
    method: "GET",
    path: "/api/site-config/brand",
    requiresAuth: false,
    allowedRoles: [],
    params: [],
    successMessage: "Site brand loaded",
  }),
  endpoint({
    id: "site-brand-update",
    category: "Site Config",
    name: "Update site brand",
    description: "Update the current site-wide brand settings.",
    method: "PUT",
    path: "/api/site-config/brand",
    requiresAuth: true,
    allowedRoles: ["admin", "designer"],
    params: [
      param("name", "Name", "body", true, "string", "Brand name."),
      param("tagline", "Tagline", "body", true, "string", "Brand tagline."),
      param("logo", "Logo", "body", true, "string", "Logo text token."),
      param("logoImage", "Logo image", "body", false, "string", "Uploaded logo image."),
      param("faviconImage", "Favicon image", "body", false, "string", "Uploaded favicon image."),
      param("primary", "Primary", "body", true, "string", "Primary hex color."),
      param("secondary", "Secondary", "body", true, "string", "Secondary hex color."),
      param("accent", "Accent", "body", true, "string", "Accent hex color."),
      param("domain", "Domain", "body", true, "string", "Brand domain."),
    ],
    successMessage: "Site brand updated",
  }),
  endpoint({
    id: "dashboard-config-get",
    category: "Site Config",
    name: "Get dashboard config",
    description: "Load dashboard preferences for a specific signed-in user key.",
    method: "GET",
    path: "/api/site-config/dashboard/:userKey",
    requiresAuth: true,
    allowedRoles: [],
    params: [
      param("userKey", "User key", "path", true, "string", "Dashboard config owner key."),
    ],
    successMessage: "Dashboard config loaded",
  }),
  endpoint({
    id: "dashboard-config-update",
    category: "Site Config",
    name: "Update dashboard config",
    description: "Persist dashboard preferences for a specific signed-in user key.",
    method: "PUT",
    path: "/api/site-config/dashboard/:userKey",
    requiresAuth: true,
    allowedRoles: [],
    params: [
      param("userKey", "User key", "path", true, "string", "Dashboard config owner key."),
      param("density", "Density", "body", true, "string", "Dashboard density setting."),
      param("focusModulePath", "Focus module path", "body", true, "string", "Pinned focus route."),
      param("showLockedModules", "Show locked modules", "body", true, "boolean", "Whether locked cards stay visible."),
      param("moduleColumns", "Module columns", "body", true, "number", "Module board column count."),
      param("widgetOrder", "Widget order", "body", true, "array", "Ordered widget ids."),
      param("hiddenWidgets", "Hidden widgets", "body", true, "array", "Hidden widget ids."),
    ],
    successMessage: "Dashboard config updated",
  }),
  endpoint({
    id: "analytics-summary",
    category: "Analytics",
    name: "Get analytics summary",
    description: "Return the analytics dashboard summary payload.",
    method: "GET",
    path: "/api/analytics/summary",
    requiresAuth: true,
    allowedRoles: ["admin", "analyst"],
    params: [],
    successMessage: "Analytics summary loaded",
  }),
];

export function getBuilderApiCatalog() {
  return BUILDER_API_CATALOG;
}
